import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( <ClerkProvider >
    <html lang="en">
      <head>
      <script src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}></script>
      </head>
     
        <body className={inter.className}>
          <Provider>
            <div className="w-full bg-white  px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64 ">
              <Header />
            </div>

            <div className=" bg-slate-100 px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64   ">
              {children}
            </div>
          </Provider>
        </body>

    </html></ClerkProvider>
  );
}
